keys:
  - &admin_atri 293B93D8A471059F85D716A65BA92099D9BE2DAA
  - &home_atri age1uaacus925f6gzw8naxasvakvvm949e4t5eflzvvhdkxqq3n34f8sa8dkp5
  - &host_sakanaa age1vkzfcwl6qwh7y3h9rhdygxy03rqy5nhfxdmqchquz7r68vm2l4wsdsexez
  - &host_Index age1u3k3tkjeh078fhhstn4q8dhw8jv95awdcnay3dnju4hu22y7evpqwfgzjq
creation_rules:
  - path_regex: secrets/cloudflare.yaml$
    key_groups:
      - pgp:
          - *admin_atri
        age:
          - *host_sakanaa
  - path_regex: secrets/ca.yaml$
    key_groups:
      - pgp:
          - *admin_atri
        age:
          - *home_atri
          - *host_Index
  - path_regex: secrets/home-[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_atri
        age:
          - *host_sakanaa
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_atri
