name: "Setup Nix & Attic"
description: "Installs Nix, configures Magic Cache, and sets up Attic"

inputs:
  attic-endpoint:
    description: "Attic Server Endpoint"
    required: false
  attic-cache:
    description: "Attic Cache Name"
    required: false
  attic-token:
    description: "Attic Authentication Token"
    required: false
  use-magic-cache:
    description: "Use Magic Cache for Nix builds"
    required: false
    default: "true"
  maximize-space:
    description: "Maximize build space (remove dotnet, android, etc)"
    required: false
    default: "true"
  tmate-debug:
    description: "Enable tmate debugging session"
    required: false
    default: "false"
  tmate-detached:
    description: "Run tmate debugging session in detached mode"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Maximize build space
      if: inputs.maximize-space == 'true'
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        swap-size-mb: 1024
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        build-mount-path: "/nix"

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          download-attempts = 10
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M=
          extra-substituters = https://nix-community.cachix.org https://cache.nixos-cuda.org

    - uses: DeterminateSystems/magic-nix-cache-action@v13
      if: inputs.use-magic-cache == 'true'
      with:
        use-flakehub: false

    - name: Setup Attic Cache
      uses: ryanccn/attic-action@v0.4.1
      if: inputs.attic-endpoint != '' && inputs.attic-cache != '' && inputs.attic-token != ''
      with:
        endpoint: ${{ inputs.attic-endpoint }}
        cache: ${{ inputs.attic-cache }}
        token: ${{ inputs.attic-token }}
        skip-push: true

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: inputs.tmate-debug == 'true'
      with:
        detached: ${{ inputs.tmate-detached }}
