name: "Build and Push to Attic"
description: "Builds a Nix attribute and pushes results to Attic."

inputs:
  name:
    description: "Display name of the artifact (e.g., package name or hostname)"
    required: true
  nix-attr:
    description: "The full Nix attribute path to build (e.g., .#packages.x86_64-linux.foo)"
    required: true
  attic-endpoint:
    description: "Attic Server Endpoint"
    required: true
  attic-cache:
    description: "Attic Cache Name"
    required: true
  attic-token:
    description: "Attic Authentication Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build and Push
      shell: bash
      env:
        ATTIC_ENDPOINT: ${{ inputs.attic-endpoint }}
        ATTIC_CACHE: ${{ inputs.attic-cache }}
        ATTIC_TOKEN: ${{ inputs.attic-token }}
        TARGET_NAME: ${{ inputs.name }}
        BUILD_ATTR: ${{ inputs.nix-attr }}
      run: |
        echo "::group::🔨 Building $TARGET_NAME"
        OUT_PATH=$(nix build -L --print-out-paths "$BUILD_ATTR" --override-input nix-secrets ./nix-secrets-dummy)
        echo "::endgroup::"

        echo "::group::🚀 Pushing to Attic"
        attic push -j 1 "$ATTIC_CACHE" "$OUT_PATH"
        echo "::endgroup::"

        echo "::group::📊 Generating Analysis"
        {
          echo "### ✅ Build Success: $TARGET_NAME"
          echo "**Path:** \`$OUT_PATH\`"
        } >> $GITHUB_STEP_SUMMARY

        if SIZE_BYTES=$(nix path-info -S "$OUT_PATH" 2>/dev/null | awk '{print $2}'); then
          TOTAL_SIZE=$(numfmt --to=iec-i --suffix=B "$SIZE_BYTES")
          echo "**Closure Size:** $TOTAL_SIZE" >> $GITHUB_STEP_SUMMARY
        else
          echo "**Closure Size:** Unknown" >> $GITHUB_STEP_SUMMARY
        fi

        {
          echo ""
          echo "<details><summary>📦 Top 10 Largest Dependencies</summary>"
          echo ""
          echo "| Size | Package |"
          echo "| :--- | :--- |"
        } >> $GITHUB_STEP_SUMMARY

        nix path-info -rs "$OUT_PATH" 2>/dev/null | sort -nk2 | tail -n 10 | tac | while read path size; do
          HUMAN_SIZE=$(numfmt --to=iec-i --suffix=B "$size")
          NAME=$(basename "$path" | cut -d- -f2-)
          echo "| $HUMAN_SIZE | $NAME |" >> $GITHUB_STEP_SUMMARY
        done || true

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
        echo "::endgroup::"
